### PR TITLE
[rfc] autotools: initial support

### PR DESCRIPTION
**Pull request by inliniac**
Mostly a copy of the Suricata files, stripped of most things.

Incomplete, as it doesn't check for jsmn yet. It does check for redis libevent2 and lua(jit).

Output of configure && make currently:
<pre>
$ bash autogen.sh && ./configure && make
Found libtoolize
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
You can now run "./configure" and then "make".
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc -std=gnu99... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc -std=gnu99 object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if gcc -std=gnu99 static flag -static works... yes
checking if gcc -std=gnu99 supports -c -o file.o... yes
checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the gcc -std=gnu99 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.21... yes
checking whether GCC or Clang is our compiler... gcc
checking gcc version... 4.8
checking for gawk... (cached) gawk
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking for python... /usr/bin/python
checking for wget... /usr/bin/wget
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking assert.h usability... yes
checking assert.h presence... yes
checking for assert.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking sched.h usability... yes
checking sched.h presence... yes
checking for sched.h... yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking for stdint.h... (cached) yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking sys/prctl.h usability... yes
checking sys/prctl.h presence... yes
checking for sys/prctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for sys/stat.h... (cached) yes
checking sys/syscall.h usability... yes
checking sys/syscall.h presence... yes
checking for sys/syscall.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for unistd.h... (cached) yes
checking for sys/ioctl.h... (cached) yes
checking linux/if_ether.h usability... yes
checking linux/if_ether.h presence... yes
checking for linux/if_ether.h... yes
checking linux/if_packet.h usability... yes
checking linux/if_packet.h presence... yes
checking for linux/if_packet.h... yes
checking linux/filter.h usability... yes
checking linux/filter.h presence... yes
checking for linux/filter.h... yes
checking linux/ethtool.h usability... yes
checking linux/ethtool.h presence... yes
checking for linux/ethtool.h... yes
checking linux/sockios.h usability... yes
checking linux/sockios.h presence... yes
checking for linux/sockios.h... yes
checking glob.h usability... yes
checking glob.h presence... yes
checking for glob.h... yes
checking for sys/socket.h... (cached) yes
checking for net/if.h... yes
checking for sys/mman.h... yes
checking for linux/if_arp.h... yes
checking for windows.h... no
checking for winsock2.h... no
checking for ws2tcpip.h... no
checking for w32api/wtypes.h... no
checking for w32api/winbase.h... no
checking for inline... inline
checking for pid_t... yes
checking for size_t... yes
checking for int32_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for gettimeofday... yes
checking for memset... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strtol... yes
checking for strtoul... yes
checking for memchr... yes
checking for memrchr... yes
checking for strlcpy... no
checking for strlcat... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking host os... installation for x86_64-unknown-linux-gnu OS... ok
checking for thread local storage __thread support... yes
checking checking if gcc supports -march=native... yes
checking for pthread_create in -lpthread... yes
checking hiredis/hiredis.h usability... yes
checking hiredis/hiredis.h presence... yes
checking for hiredis/hiredis.h... yes
checking for redisConnect in -lhiredis... yes
checking event2/listener.h usability... yes
checking event2/listener.h presence... yes
checking for event2/listener.h... yes
checking for evconnlistener_enable in -levent... yes
checking for getconf... /usr/bin/getconf
checking for git... /usr/bin/git
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

Mobster Configuration:
  libjansson support:                      
  hiredis support:                         yes
  LUA support:                             no
  libluajit:                               no
  Debug output enabled:                    no

Generic build parameters:
  Installation prefix:                     /usr/local
  Configuration directory:                 /usr/local/etc/mobster/
  Log directory:                           /usr/local/var/log/mobster/

  --prefix                                 /usr/local
  --sysconfdir                             /usr/local/etc
  --localstatedir                          /usr/local/var

  Host:                                    x86_64-unknown-linux-gnu
  Compiler:                                gcc (exec name) / gcc (real)
  GCC Protect enabled:                     no
  GCC march native enabled:                yes
  GCC Profile enabled:                     no
  Position Independent Executable enabled: no
  CFLAGS                                   -g -O2 -march=native
  PCAP_CFLAGS                              
  SECCFLAGS                                

To build and install run 'make' and 'make install'.
make  all-recursive
make[1]: Entering directory `/home/victor/sync/devel/3rdparty/mobster'
Making all in src
make[2]: Entering directory `/home/victor/sync/devel/3rdparty/mobster/src'
  CC       event_handlers.o
  CC       event_publisher.o
event_publisher.c:41:18: fatal error: jsmn.h: No such file or directory
 #include "jsmn.h"
                  ^
compilation terminated.
make[2]: *** [event_publisher.o] Error 1
make[2]: Leaving directory `/home/victor/sync/devel/3rdparty/mobster/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/victor/sync/devel/3rdparty/mobster'
make: *** [all] Error 2
</pre>

### CODE REVIEW

**Comment by inliniac** [comment]
Would it make sense to not use jsmn at all and go straight to suricata->redis->mobster?

**Comment by packetchaser** [comment]
Yes, absolutely.  I was going to ask you and Eric if you would consider routing the pub/sub to redis based on the event type.  The Redis convention for publishing to a channel is "ABC:xyz", where ABC is the major distinguisher and "xyz" is the minor.  So for Suricata breaking it out into separate channels like "EVE:flow", "EVE:tls", "EVE:alert", etc, etc would fit the convention.  What do you think?

--Randy

**Comment by inliniac** [comment]
Not sure how @regit's code does it currently. Eric, any insights?

**Comment by packetchaser** [comment]
On Nov 16, 2015, at 11:15 AM, Victor Julien <notifications@github.com> wrote:

> Not sure how @regit's code does it currently. Eric, any insights?
> 
> �
> Reply to this email directly or view it on GitHub.
> 

I believe is publishes everything to one channel.  Perhaps, this can be configurable, i.e. publish all the events to one channel or split it out based on "EVE:event_type".

--Randy

**Comment by regit** [comment]
@packetchaser you just need to have multiple eve-log entries:
```YAML
  - eve-log:
      enabled: yes
      filetype: redis
      redis:
        server: 127.0.0.1
        port: 6379
        mode: channel ## possible values: list (default), channel
        key: alert ## key or channel to use (default to suricata)
      types:
        - alert
  - eve-log:
      enabled: yes
      filetype: redis
      redis:
        server: 127.0.0.1
        port: 6379
        mode: channel
        key: smtp 
      types:
        - smtp:
```

**Comment by packetchaser** [comment]
Perfect.  I'll test it out in the next day or two.

--Randy

**Comment by packetchaser** [comment]
Thanks for incorporating autostools support.

**Comment by packetchaser** [comment]
@regit I pulled the latest suricata from github and built it with "--enable-hiredis".  However, I get the following error when I try to start suricata:

>root@raspberrypi:/home/randy/github/suricata/src# /usr/local/bin/suricata -c /etc/suricata/suricata.yaml --disable-detection -i eth0 -D
>[8667] 21/11/2015 -- 20:20:20 - (suricata.c:1386) <Info> (ParseCommandLine) -- detection engine disabled
>[8667] 21/11/2015 -- 20:20:20 - (conf-yaml-loader.c:178) <Error> (ConfYamlParse) -- [ERRCODE: SC_ERR_CONF_YAML_ERROR(242)] - Failed to parse configuration file at line 89: found character that cannot start any token


Line 89 -- "found character that cannot start any token" -- is the line beginning with "redis:" in the following YAML block:

```YAML
  - eve-log:
      enabled: yes
      filetype: redis
      redis:
        server: 127.0.0.1
        port: 6379
        mode: channel ## possible values: list (default), channel
        key: alert ## key or channel to use (default to suricata)
      types:
        - alert
```

**Comment by regit** [comment]
@packetchaser you may have introduce a tabulation instead of space. Usually this is the explanation of this message.

**Pull request merged**
